const menuItems = [
  {
    name: 'KFC Large Bucket',
    price: 500,
    rating: 4.5,
    image: 'https://content.jdmagicbox.com/v2/comp/bangalore/s9/080pxx80.xx80.220610223727.l3s9/catalogue/kfc-kattegenahalli-bangalore-quick-bites-outlets-e2brro0jrg.jpg',
    category: 'non-veg',
  },
  {
    name: 'Burger - Cold-Drink Combo!!! ',
    price: 300,
    rating: 4.4,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSAyTHBtdfBMJ4mJEcv7P903ys8T2wR5_gRg&s',
    category: 'non-veg',
  },
  {
    name: 'Kulfi',
    price: 300,
    rating: 4.4,
    image: 'https://i.ytimg.com/vi/lvQn9VNjqkM/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLALwKZ-oRL5CXW9ZgKPT_vGFnl6KA',
    category: 'veg',
  },
  {
    name: 'Sushi',
    price: 350,
    rating: 4.1,
    image: 'https://cdn.britannica.com/52/128652-050-14AD19CA/Maki-zushi.jpg',
    category: 'non-veg',
  },
  {
    name: 'Tandoori Chicken',
    price: 320,
    rating: 4.7,
    image: 'https://www.allrecipes.com/thmb/ygY1JXP8_IkDSjPPW5VH2dTiMMU=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/50347-indian-tandoori-chicken-DDMFS-4x3-3035-205e98c80b2f4275b5bd010c396d9149.jpg',
    category: 'non-veg',
  },
  {
    name: 'Paneer Butter Masala',
    price: 250,
    rating: 4.2,
    image: 'https://www.cookwithmanali.com/wp-content/uploads/2019/05/Paneer-Butter-Masala.jpg',
    category: 'veg',
  },
  {
    name: 'Chicken Biryani',
    price: 300,
    rating: 4.6,
    image: 'https://www.cubesnjuliennes.com/wp-content/uploads/2020/07/Chicken-Biryani-Recipe.jpg',
    category: 'non-veg',
  },
  {
    name: 'Masala Dosa',
    price: 120,
    rating: 4.4,
    image: 'https://static01.nyt.com/images/2015/01/28/dining/28KITCHEN1/28KITCHEN1-superJumbo.jpg',
    category: 'veg',
  },
  {
    name: 'Coffee',
    price: 120,
    rating: 4.4,
    image: 'https://www.netmeds.com/images/cms/wysiwyg/blog/Post/2018/10/coffee_its_benefits_898_1_.jpg',
    category: 'drinks',
  },
  {
    name: 'Chole Bhature',
    price: 150,
    rating: 4.3,
    image: 'https://img-global.cpcdn.com/steps/bf31adeca966e194/400x400cq70/photo.jpg',
    category: 'veg',
  },
  {
    name: 'Gulab Jamun',
    price: 90,
    rating: 4.5,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3aJrkMZfZWaRkqQu36Y9TBzYlCrkKHvy7mw&s',
    category: 'veg',
  },
  {
    name: 'Butter Chicken',
    price: 320,
    rating: 4.7,
    image: 'https://www.mysavoryadventures.com/wp-content/uploads/2023/04/restaurant-style-butter-chicken.jpg',
    category: 'non-veg',
  },
  {
    name: 'Rogan Josh',
    price: 350,
    rating: 4.3,
    image: 'https://img.taste.com.au/TFQ_zAsZ/taste/2017/06/lamb-rogan-josh-127388-1.jpg',
    category: 'non-veg',
  },
  {
    name: 'Malai Kofta',
    price: 270,
    rating: 4.2,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4cnHdUfexvHPI4ohvfY5-sDAZe1taV9_RHg&s',
    category: 'veg',
  },
  {
    name: 'Pani Puri',
    price: 50,
    rating: 4.6,
    image: 'https://www.sidechef.com/recipe/3883dffb-5fa2-4ee9-8054-d8de1409899f.jpg?d=1408x1120',
    category: 'veg',
  },
  {
    name: 'Aloo Tikki',
    price: 60,
    rating: 4.4,
    image: 'https://www.cubesnjuliennes.com/wp-content/uploads/2020/08/Crispy-Aloo-Tikki-Recipe.jpg',
    category: 'veg',
  },
  {
    name: 'Litti Chokha',
    price: 80,
    rating: 4.1,
    image: 'https://static.toiimg.com/thumb/53188495.cms?width=1200&height=900',
    category: 'veg',
  },
  {
    name: 'Momos',
    price: 100,
    rating: 4.3,
    image: 'https://www.chefadora.com/_next/image?url=https%3A%2F%2Fchefadora.b-cdn.net%2Fmedium_931_DFCAA_1_C48_4496_B851_1_AD_52_DC_74233_4597b7d9e8.jpeg&w=3840&q=75',
    category: 'non-veg',
  },
  {
    name: 'Papdi Chaat',
    price: 70,
    rating: 4.2,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlag9_G-LxVguLzQi5164a8iG00U49rDszOA&s',
    category: 'veg',
  },
  {
    name: 'Poha Jalebi',
    price: 90,
    rating: 4.4,
    image: 'https://images.slurrp.com/prod/articles/hfcq8gy17p5.webp',
    category: 'veg',
  },
  {
    name: 'Shahi Paneer',
    price: 280,
    rating: 4.5,
    image: 'https://indianshealthyrecipes.com/wp-content/uploads/2024/07/ShahiPaneer-3.jpg',
    category: 'veg',
  },
  {
    name: 'Mutton Curry',
    price: 350,
    rating: 4.6,
    image: 'https://www.licious.in/blog/wp-content/uploads/2023/02/shutterstock_2205168763.jpg',
    category: 'non-veg',
  },
  {
    name: 'Fish Curry',
    price: 300,
    rating: 4.4,
    image: 'https://stewwithsaba.com/wp-content/uploads/2024/05/IMG_4409-edited.jpg',
    category: 'non-veg',
  },
  {
    name: 'Vegetable Korma',
    price: 220,
    rating: 4.1,
    image: 'https://thebigmansworld.com/wp-content/uploads/2022/11/vegetable-korma-recipe.jpg',
    category: 'veg',
  },
  {
    name: 'Tandoori Chicken',
    price: 320,
    rating: 4.7,
    image: 'https://www.allrecipes.com/thmb/ygY1JXP8_IkDSjPPW5VH2dTiMMU=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/50347-indian-tandoori-chicken-DDMFS-4x3-3035-205e98c80b2f4275b5bd010c396d9149.jpg',
    category: 'non-veg',
  },
  {
    name: 'Naan',
    price: 40,
    rating: 4.3,
    image: 'https://fullofplants.com/wp-content/uploads/2023/05/Homemade-Naan-Bread-Restaurant-Style-Vegan-thumb-1-500x500.jpg',
    category: 'veg',
  },
  {
    name: 'Lassi',
    price: 60,
    rating: 4.5,
    image: 'https://themagicsaucepan.com/wp-content/uploads/2018/05/20180511-salt-lassi-0061-500x500.jpg',
    category: 'drinks',
  },
  {
    name: 'Jalebi',
    price: 50,
    rating: 4.6,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRD12OCxU4Th3aX7Mj3vPBcnVJEf5WhIAzWEQ&s',
    category: 'veg',
  },
  {
    name: 'Cake',
    price: 250,
    rating: 4.2,
    image: 'https://ocakes.in/storage/app/public/images/item/item-667ab251cac30.webp',
    category: 'veg',
  },
];

export default menuItems;
